# Generated by Django 3.2.10 on 2022-02-14 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('btest', '0003_auto_20220214_0813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rubric',
            options={'ordering': ['name'], 'verbose_name': 'Поезд', 'verbose_name_plural': 'Поезда'},
        ),
        migrations.AlterField(
            model_name='bb',
            name='rubric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='btest.rubric', verbose_name='Поезд'),
        ),
    ]
